# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name sclineager_gibbs
#' @title An internal function for Gibbs sampling
#' @description An internal function for Gibbs sampling wrapped by \link{sclineager_internal}
#' @seealso \link{sclineager_internal}
#' @exports
sclineager_gibbs <- function(psi, k_mat, transform_mat, mu, dfreedom, sigma, max_iter = 100L, save = FALSE) {
    .Call('_SClineager_sclineager_gibbs', PACKAGE = 'SClineager', psi, k_mat, transform_mat, mu, dfreedom, sigma, max_iter, save)
}

