// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sclineager_gibbs
Rcpp::List sclineager_gibbs(arma::mat psi, arma::mat k_mat, arma::mat transform_mat, arma::vec mu, int dfreedom, arma::mat sigma, int max_iter, bool save);
RcppExport SEXP _SClineager_sclineager_gibbs(SEXP psiSEXP, SEXP k_matSEXP, SEXP transform_matSEXP, SEXP muSEXP, SEXP dfreedomSEXP, SEXP sigmaSEXP, SEXP max_iterSEXP, SEXP saveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type k_mat(k_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type transform_mat(transform_matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type dfreedom(dfreedomSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type save(saveSEXP);
    rcpp_result_gen = Rcpp::wrap(sclineager_gibbs(psi, k_mat, transform_mat, mu, dfreedom, sigma, max_iter, save));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SClineager_sclineager_gibbs", (DL_FUNC) &_SClineager_sclineager_gibbs, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_SClineager(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
